name: Deploy NGINX

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Prueba3/**'

env:
  DOCKER_IMAGE: craft-nginx
  K8S_NAMESPACE: craft-actions
  K8S_DEPLOYMENT: ct-nginx
  REPOSITORY: lucasblanco/craft-nginx
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Prueba3/
          push: true
          tags: lucasblanco/craft-nginx:latest, lucasblanco/craft-nginx:${{ github.sha }}
