name: Deploy NGINX

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'Prueba3/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Prueba3/
          push: true
          tags: lucasblanco/craft-nginx:latest, lucasblanco/craft-nginx:${{ github.sha }}
  
  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        commands: -n dev set image deployment/nginx nginx=lucasblanco/craft-nginx:latest
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        version: v1.21.2
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        commands: -n dev rollout status deployment/nginx