name: Deploy NGINX

on:
  push:
    branches:
      - 'master'

env:
  DOCKER_IMAGE: craft-nginx
  K8S_NAMESPACE: craft-actions
  K8S_DEPLOYMENT: ct-nginx
  REPOSITORY: lucasblanco/craft-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Prueba3/
          push: true
          tags: lucasblanco/craft-nginx:latest, lucasblanco/craft-nginx:${{ github.sha }}
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy 
        run: kubectl set image deployment $K8S_DEPLOYMENT -n $K8S_NAMESPACE $K8S_DEPLOYMENT=$REPOSITORY:${{ github.sha }}